### ISSUE TITLE
Projects Section Should route to Login Page

### ISSUE THREAD

**Issue by devarshishimpi** [devarshishimpi/devcode#35]
When User clicks on `/projects` in the **navbar** or **footer** then it should redirect to `/projects` page, and if not logged in, then it should redirect to `/login` page

@abhinandanwadwa Kindly take on the issue and finish it till tomorrow ( Urgent fix required )

**Comment by abhinandanwadwa** [comment]
I'll fix this within an hour or so.

**Comment by devarshishimpi** [comment]
Fixed
