### ISSUE TITLE
🐛 [BUG] - `Features` link in Nav bar & Footer not working

### ISSUE THREAD

**Issue by inclinedadarsh** [devarshishimpi/devcode#38]
### Description

It's just that, the link in the nav bar and footer isn't working

I can fix it if you want

### Reproduction URL

https://github.com/dvstechlabs/Devcode

### Reproduction steps

```bash
Idk what should I write here.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

**Comment by devarshishimpi** [comment]
Thanks @inclinedadarsh Yes, you can work on this, Have assigned you

**Comment by devarshishimpi** [comment]
Fixed
