### ISSUE TITLE
Add a loader to buttons when there is an api call in process

### ISSUE THREAD

**Issue by abhinandanwadwa** [devarshishimpi/devcode#52]
### Summary

Whenever we call the Devcode api, there should be loader icon spinning and the button should be disabled unti api returns the data, so that the user gets to know that something is happening on the website, rather than a blank button. This also prevents duplicate entry. You can fix this by adding a new state variable.

### Basic Example

For example, when submitting a project, there should be a loader added on the button until data is not fetched.

**Comment by byte-king** [comment]
Hi @abhinandanwadwa, I want to work on this issue.

**Comment by abhinandanwadwa** [comment]
Go ahead @byte-king!. I've assigned you this issue.

**Comment by abhinandanwadwa** [comment]
@byte-king how's the progress?

**Comment by devarshishimpi** [comment]
> @byte-king how's the progress?

I think this issue is already completed. Check it if I am right.

**Comment by abhinandanwadwa** [comment]
> > @byte-king how's the progress?
> 
> I think this issue is already completed. Check it if I am right.

No, it's not completed yet

**Comment by devarshishimpi** [comment]
> > > @byte-king how's the progress?
> > 
> > 
> > I think this issue is already completed. Check it if I am right.
> 
> No, it's not completed yet

What's the loader on `/projects` section? and the infinite scroll

**Comment by abhinandanwadwa** [comment]
> > > > @byte-king how's the progress?
> > > 
> > > 
> > > I think this issue is already completed. Check it if I am right.
> > 
> > 
> > No, it's not completed yet
> 
> What's the loader on `/projects` section? and the infinite scroll

It's `loader to buttons` when there is an API call

**Comment by byte-king** [comment]
> @byte-king how's the progress?

Hey @abhinandanwadwa, Sorry I was travelling last week so couldn't complete it. Will try to complete it by this week.

**Comment by byte-king** [comment]
I have completed the task.
 What should I do next? @devarshishimpi @abhinandanwadwa

**Comment by abhinandanwadwa** [comment]
@byte-king Make a PR from your branch with your changes. Make sure to sync your fork first.

**Comment by byte-king** [comment]
@abhinandanwadwa , wouldn't it be easier for the user if I add a text in the button which shows that the project is being added instead of the loading icon? 

https://user-images.githubusercontent.com/55686016/213989790-b3e6ac3c-a376-4505-92c7-5b412b65a57a.mp4

**Comment by abhinandanwadwa** [comment]
> @abhinandanwadwa , wouldn't it be easier for the user if I add a text in the button which shows that the project is being added instead of the loading icon? 
> 
> https://user-images.githubusercontent.com/55686016/213989790-b3e6ac3c-a376-4505-92c7-5b412b65a57a.mp4
> 
> 
> 
> 

The loader would be much easier for the user to understand that it's processing.

**Comment by byte-king** [comment]
Okay.
