### ISSUE TITLE
Loading Page for the site💡 

### ISSUE THREAD

**Issue by prakhar-1005** [devarshishimpi/devcode#63]
### Start Date

feb/06/2023

### Summary

A loading page for this site would enhance the user experience.

### Basic Example

Adding a loading page for the site

### Drawbacks

It may seem that the site is taking longer to load but it won't have much affect.

**Comment by geeky-sambhav** [comment]
I would like to contribute on this issue

**Comment by devarshishimpi** [comment]
> I would like to contribute on this issue

That's great! I have assigned you the issue
