### ISSUE TITLE
error in Loader.jsx file. The imported CSS file has typing error.

### ISSUE THREAD

**Issue by AniketNS** [devarshishimpi/devcode#67]
### What would you like to share?

There is an error in Loader.jsx file. The imported CSS file has typing error. 

The import statement should be `import "./loader.css"` not `import "./Loader.css"`

<img width="823" alt="devcode loader css error" src="https://github.com/bytemakers/Devcode/assets/91371143/79a0aedd-80b6-427b-a8fc-f70fddab0faf">

### Additional information

I've corrected the typo and I'll create the PR for it. Please check and get it merged.

**Comment by devarshishimpi** [comment]
Fixed
